<?php
/**
 * swap body layout classes
 * @see https://github.com/bigskysoftware/htmx/issues/1384#issuecomment-1727785708
 */
?>
<script>
    document.body.addEventListener('htmx:afterSwap', function(evt) {
        const parser = new DOMParser();
        const parsedResponse = parser.parseFromString(evt.detail.xhr.response, "text/html");
        const bodyAttributes = parsedResponse.getElementsByTagName('body')[0].attributes;
        for (const attribute of bodyAttributes) {
            document.body.setAttribute(attribute.name, attribute.value);
        }
        jQuery.mage.init();
        // need a way to init message again
        require(['jquery', 'Magento_Customer/js/customer-data', 'underscore'], function ($, customerData, _) {
            var messages = $.cookieStorage.get('mage-messages');
            if (!_.isEmpty(messages)) {
                customerData.set('messages', {messages: messages});
                $.cookieStorage.set('mage-messages', '');
            }
        });
    });
</script>
